<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link href='https://fonts.googleapis.com/css?family=Amiri' rel='stylesheet'>        
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" href="footerstyle.css">
</head>
<footer>
    <div class="footer-info">
        <div class="first-info">
            <img src="images/logo.png" alt="">

            <p>10 Dover Drive, <br> Singapore 138683</p>
            <p>+65 9313 4274</p>
            <p>info@wildflower.com</p>

        </div>

        <div class="second-info">
            <h4>Navigate</h4>
            <p><a href="home.php">Home</a></p>
            <p><a href="shop.php">Shop</a></p>
            <p><a href="aboutus.php">About</a></p>
            <p><a href="contact.php">Contact</a></p>
        </div>

        <div class="third-info">
            <h4>Membership</h4>
            <p><a href="#">Account</a></p>
            <p><a href="#">Membership Benefit</a></p>
            <p><a href="#">Affiliate Links</a></p>
            <p><a href="#">Login</a></p>
        </div>

        <div class="forth-info">
            <h4>Thank You</h4>
            <p>We truly appreciate your decision to choose us as your preferred  
            <br>supplier and your efforts in spreading the word about our 
            <br>products/services to your friends, family, and colleagues. 
        </div>
    </div>

<div class="end-text">
    <p>Copyrights © Protection 2020. All Rights Reserved. Designd By Tong Lee Millionaire.</p>
</div>
    
</footer>