<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wildflower Soap</title>
    <link href='https://fonts.googleapis.com/css?family=Amiri' rel='stylesheet'>        
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" href="headerstyle.css">
</head>

    <div class="banner">
        <div class="banner-content" style="text-align: center">
            <p>Islandwide delivery. Free shipping over $60nett. Use promocode: 'rizzler' for 10% off</p>
        </div>
    </div>

<header>
    <a href="home.php" class="logo"><img src="images/logo.png" alt=""></a>
        
    <ul class="navbar">
        <li><a href="home.php">Home</a></li>
        <li><a href="shop.php">Shop</a></li>
        <li><a href="aboutus.php">About</a></li>
        <li><a href="contact.php">Contact</a></li>
    </ul>

        <div class="nav-icon">
            <a href="cart-page.php"><i class='bx bx-cart'></i></a>
    </div>
</header>